# Generated by Django 5.2.18 on 2026-10-08 09:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mentor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, verbose_name="שם")),
                (
                    "phone",
                    models.CharField(
                        help_text="בפורמט \u200e+9725…",
                        max_length=20,
                        unique=True,
                        verbose_name="טלפון",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "לא נפנה"),
                            ("contacted", "נשלחה פנייה"),
                            ("replied", "ענה"),
                            ("interested", "מתעניין"),
                            ("reported", "דיווח שהגיש"),
                            ("verified", "הגשה מאומתת"),
                            ("declined", "לא מעוניין"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="סטטוס",
                    ),
                ),
                (
                    "opted_out",
                    models.BooleanField(default=False, verbose_name="ביקש הסרה"),
                ),
                (
                    "needs_human",
                    models.BooleanField(default=False, verbose_name="צריך מענה אנושי"),
                ),
                (
                    "bot_paused",
                    models.BooleanField(
                        default=False,
                        help_text="נחמה לא עונה למנחה הזה. צוות מטפל ידנית.",
                        verbose_name="נחמה מושתקת",
                    ),
                ),
                (
                    "outreach_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="מונה פניות"
                    ),
                ),
                (
                    "last_outreach_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="פנייה אחרונה"
                    ),
                ),
                (
                    "last_inbound_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="הודעה אחרונה מהמנחה"
                    ),
                ),
                (
                    "last_activity_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="פעילות אחרונה",
                    ),
                ),
                (
                    "preferences",
                    models.TextField(blank=True, verbose_name="העדפות (נחמה ממלאת)"),
                ),
                (
                    "summary",
                    models.TextField(
                        blank=True, verbose_name="סיכום שיחה (נחמה ממלאת)"
                    ),
                ),
                (
                    "staff_notes",
                    models.TextField(blank=True, verbose_name="הערות צוות"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("list", "רשימה"), ("inbound", "פנה בעצמו")],
                        default="list",
                        max_length=20,
                        verbose_name="מקור",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "מנחה",
                "verbose_name_plural": "מנחים",
                "ordering": ["-last_activity_at", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "registration_link",
                    models.URLField(blank=True, verbose_name="קישור הרשמה להנחייה"),
                ),
                (
                    "context_doc_url",
                    models.URLField(
                        blank=True,
                        help_text="המסמך צריך להיות משותף כ'כל מי שיש לו את הקישור יכול לצפות'.",
                        verbose_name="קישור למסמך ההקשר (Google Docs)",
                    ),
                ),
                (
                    "context_fallback",
                    models.TextField(
                        blank=True,
                        help_text="מתעדכן אוטומטית מהמסמך. משמש אם Google לא זמין.",
                        verbose_name="עותק גיבוי של מסמך ההקשר",
                    ),
                ),
                (
                    "extra_instructions",
                    models.TextField(
                        blank=True,
                        help_text="מתווסף להנחיות הקבועות. לא חובה.",
                        verbose_name="הנחיות נוספות לנחמה",
                    ),
                ),
                (
                    "bot_enabled",
                    models.BooleanField(default=True, verbose_name="נחמה עונה להודעות"),
                ),
                (
                    "outreach_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="כבוי כברירת מחדל. כשדולק, נחמה שולחת פניות ותזכורות למנחים ברשימה.",
                        verbose_name="פנייה יזומה פעילה",
                    ),
                ),
                (
                    "reminder_days",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="ימים בין תזכורות"
                    ),
                ),
                (
                    "max_outreach",
                    models.PositiveSmallIntegerField(
                        default=3, verbose_name="מקסימום פניות למנחה"
                    ),
                ),
                (
                    "reservation_days",
                    models.PositiveSmallIntegerField(
                        default=7, verbose_name="ימי תפוגת שריון"
                    ),
                ),
                (
                    "outreach_batch",
                    models.PositiveSmallIntegerField(
                        default=25, verbose_name="מקסימום פניות בכל ריצה"
                    ),
                ),
                (
                    "send_hour_start",
                    models.PositiveSmallIntegerField(
                        default=10, verbose_name="שעת התחלה לפניות"
                    ),
                ),
                (
                    "send_hour_end",
                    models.PositiveSmallIntegerField(
                        default=20, verbose_name="שעת סיום לפניות"
                    ),
                ),
                (
                    "first_template_sid",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        verbose_name="Content SID – פנייה ראשונה",
                    ),
                ),
                (
                    "reminder_template_sid",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="Content SID – תזכורת"
                    ),
                ),
                (
                    "first_template_text",
                    models.TextField(
                        blank=True,
                        help_text="לתיעוד בשיחה. [שם] יוחלף בשם המנחה.",
                        verbose_name="טקסט הפנייה הראשונה",
                    ),
                ),
                (
                    "reminder_template_text",
                    models.TextField(blank=True, verbose_name="טקסט התזכורת"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "הגדרות",
                "verbose_name_plural": "הגדרות",
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="קצר וקבוע, למשל G01",
                        max_length=20,
                        unique=True,
                        verbose_name="מזהה",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="שם")),
                (
                    "system",
                    models.CharField(blank=True, max_length=100, verbose_name="מערכת"),
                ),
                (
                    "genre",
                    models.CharField(blank=True, max_length=100, verbose_name="ז'אנר"),
                ),
                (
                    "audience",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="קהל יעד"
                    ),
                ),
                (
                    "ages",
                    models.CharField(blank=True, max_length=30, verbose_name="גילאים"),
                ),
                (
                    "players_min",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="שחקנים מינימום"
                    ),
                ),
                (
                    "players_max",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="שחקנים מקסימום"
                    ),
                ),
                (
                    "duration",
                    models.CharField(blank=True, max_length=30, verbose_name="משך"),
                ),
                (
                    "experience",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("beginner", "מתחיל"),
                            ("intermediate", "בינוני"),
                            ("experienced", "מנוסה"),
                        ],
                        max_length=20,
                        verbose_name="ניסיון נדרש מהמנחה",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="זה מה שנחמה מציגה למנחה",
                        verbose_name="תיאור קצר",
                    ),
                ),
                (
                    "materials_url",
                    models.URLField(blank=True, verbose_name="קישור לחומרים"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("free", "פנוי"),
                            ("reserved", "שוריין"),
                            ("assigned", "שובץ"),
                        ],
                        default="free",
                        max_length=20,
                        verbose_name="סטטוס שיבוץ",
                    ),
                ),
                (
                    "reserved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="תאריך שריון"
                    ),
                ),
                (
                    "reserved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="games",
                        to="recruit.mentor",
                        verbose_name="משוריין ל",
                    ),
                ),
            ],
            options={
                "verbose_name": "משחק",
                "verbose_name_plural": "משחקים",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "נכנסת"), ("out", "יוצאת")], max_length=3
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        choices=[
                            ("mentor", "מנחה"),
                            ("nechama", "נחמה"),
                            ("staff", "צוות"),
                            ("template", "תבנית פנייה"),
                            ("system", "מערכת"),
                        ],
                        max_length=10,
                    ),
                ),
                ("body", models.TextField(blank=True)),
                (
                    "twilio_sid",
                    models.CharField(blank=True, max_length=64, null=True, unique=True),
                ),
                ("delivery_status", models.CharField(blank=True, max_length=20)),
                ("error", models.CharField(blank=True, max_length=255)),
                ("processed", models.BooleanField(default=True)),
                ("status_after", models.CharField(blank=True, max_length=20)),
                ("staff_user", models.CharField(blank=True, max_length=150)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "mentor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="recruit.mentor",
                    ),
                ),
            ],
            options={
                "verbose_name": "הודעה",
                "verbose_name_plural": "הודעות",
                "ordering": ["created_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["mentor", "created_at"],
                        name="recruit_mes_mentor__a0dfb9_idx",
                    )
                ],
            },
        ),
    ]
